"""add_thread_fields_to_posts

Revision ID: 31cb28e7ebac
Revises: b7532f0cf3c8
Create Date: 2026-07-27 20:34:19.361536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31cb28e7ebac'
down_revision: Union[str, None] = 'b7532f0cf3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thread_id', sa.UUID(), nullable=True))
    op.add_column('posts', sa.Column('thread_position', sa.SmallInteger(), nullable=True))
    op.create_index(op.f('ix_posts_thread_id'), 'posts', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_thread_id'), table_name='posts')
    op.drop_column('posts', 'thread_position')
    op.drop_column('posts', 'thread_id')
    # ### end Alembic commands ###
