"""make user university_id nullable

Revision ID: 39874d268382
Revises: p98765432116
Create Date: 2026-08-11 09:54:40.531537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39874d268382'
down_revision: Union[str, None] = 'p98765432116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'university_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'university_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
